[package]
name = "postgres-tls"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio-postgres = "0.7.10"
rustls = "0.21.8"
tokio-postgres-rustls = "0.10.0"
rustls-native-certs = "0.6.3"
postgres-openssl = "0.5.0"
openssl = "0.10.57"
tokio = { version = "1.33.0", features = ["full"] }
